create table if not exists public.ranking (
  id bigint generated by default as identity primary key,
  "Nombre" text not null check (char_length("Nombre") between 1 and 40),
  puntos integer not null,
  created_at timestamptz not null default now()
);

alter table public.ranking enable row level security;

drop policy if exists ranking_select_all on public.ranking;
create policy ranking_select_all
on public.ranking
for select
using (true);

drop policy if exists ranking_insert_all on public.ranking;
create policy ranking_insert_all
on public.ranking
for insert
with check (true);
